export const items = [
    { id: 1, title: 'Team Project', tag: ['mix'], img: '../assets/images/img1.jpg' },
    { id: 2, title: 'Team Project', tag: ['design'], img: '../assets/images/img2.jpg' },
    { id: 3, title: 'Personal Project', tag: ['coding'], img: '../assets/images/img3.jpg' },
    { id: 4, title: 'Personal Project', tag: ['mix'], img: '../assets/images/img4.jpg' },
    { id: 5, title: 'Group Project', tag: ['design'], img: '../assets/images/img5.jpg' },
    { id: 6, title: 'Group Project', tag: ['mix'], img: '../assets/images/img1.jpg' },
    { id: 7, title: 'Personal Project', tag: ['design'], img: '../assets/images/img2.jpg' },
    { id: 8, title: 'Personal Project', tag: ['design'], img: '../assets/images/img2.jpg' },
    { id: 9, title: 'Personal Project', tag: ['design'], img: '../assets/images/img2.jpg' },
    { id: 10, title: 'Personal Project', tag: ['coding'], img: '../assets/images/img3.jpg' },
    { id: 11, title: 'Personal Project', tag: ['mix'], img: '../assets/images/img4.jpg' },
    { id: 12, title: 'Personal Project', tag: ['coding'], img: '../assets/images/img5.jpg' },
    { id: 13, title: 'Personal Project', tag: ['design'], img: '../assets/images/img6.jpg' },
    { id: 14, title: 'Personal Project', tag: ['coding'], img: '../assets/images/img5.jpg' },
    { id: 15, title: 'Personal Project', tag: ['coding'], img: '../assets/images/img5.jpg' },
];
